---
title: "march_april_ndgraphs"
author: "Sefa Ozalp"
date: "2020-05-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Data Ingest

```{r}
library(tidyverse)
library(dygraphs)
library(xts)
knitr::opts_chunk$set(fig.width=11, fig.height=6) 

```



```{r}

read_and_merge <- function(path){
   data <- read_csv(path,
                 col_types = cols_only(text='c', 
                                       created_at='?', 
                                       pattern_asian_bool = "l",
                                       pattern_asian_match = "c", 
                                       is_retweet = "l")
)
  return(data)

}

data <- read_and_merge("/Users/sefaozalp/Downloads/march_2020_aggregated_brief.csv") %>% 
  filter(pattern_asian_bool == TRUE)

pattern_slurs <- jsonlite::read_json("data/patterns/pattern_asian_slursonly.json") %>% 
  paste0(collapse = "|") %>% 
  stringr::str_to_lower() %>% 
  paste0("")


data_processed <- data %>% 
      mutate(
      pattern_asian_slur_bool= ifelse(stringr::str_detect(text, 
                                                     regex(pattern_slurs, 
                                                           ignore_case = TRUE)), 
                                 TRUE,FALSE),
      pattern_asian_slur_match = stringr::str_match_all(text, 
                                                        regex(pattern_slurs, 
                                                              ignore_case = TRUE))
      )


to_xts <- data_processed %>% 
  # filter_at(vars(contains("bool")), any_vars(.==TRUE)) %>%
  rtweet::ts_data(by="hours") %>% 
  rename(asian_tweet_count= n) %>% 
  left_join( data_processed %>% 
              filter(pattern_asian_slur_bool ) %>% 
              rtweet::ts_data(by="hours") %>% 
              rename(asian_slur_tweet_count= n),
             by = "time") %>% 
  mutate_if(is.integer,  ~replace_na(., 0))



data_xts <- as.xts(to_xts[-1], order.by = (to_xts$time))
# data_xts$asian_tweet_count= as.integer(data_xts$asian_tweet_count)

```


```{r}
dyUnzoom <-function(dygraph) {
  dyPlugin(
    dygraph = dygraph,
    name = "Unzoom",
    path = system.file("plugins/unzoom.js", package = "dygraphs")
  )
}


dyCrosshair <- function(dygraph, 
                        direction = c("both", "horizontal", "vertical")) {
  dyPlugin(
    dygraph = dygraph,
    name = "Crosshair",
    path = system.file("plugins/crosshair.js", 
                       package = "dygraphs"),
    options = list(direction = match.arg(direction))
  )
}

```

# Covid Tweets and Identities 

```{r}
data_xts$asian_slur_tweet_count %>% 
  # head(100) %>% 
  dygraph(main = "Tweets Matching The Identity Patterns") %>% 
  dyRangeSelector() %>% 
  dyOptions(drawPoints = TRUE, pointSize = 1) %>% 
  dyRangeSelector(height = 50) %>% 
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE) %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  dyLegend(show = "always", hideOnMouseOut = TRUE, labelsSeparateLines = TRUE) %>%    
  dyUnzoom() %>% 
  dyCrosshair() %>% 
  dyOptions(colors = RColorBrewer::brewer.pal(4, "Set1"))
```

## Covid Tweets and Identities with 24H roll
 
```{r}
data_xts$asian_slur_tweet_count%>% 
  # head(100) %>% 
  dygraph(main = "Tweets Matching The Identity Patterns 24H Roll") %>% 
  dyRangeSelector() %>% 
  dyOptions(drawPoints = TRUE, pointSize = 1) %>% 
  dyRangeSelector(height = 50) %>% 
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE) %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  dyRoller(rollPeriod = 24) %>% 
  dyUnzoom() %>% 
  dyCrosshair() %>% 
  dyOptions(colors = RColorBrewer::brewer.pal(4, "Set1"))
```
 

# Covid Tweets With Sums
```{r, eval=F}

data_xts %>% 
  # head(100) %>% 
  dygraph(main = "Tweets Matching The Identity Patterns") %>% 
  dyRangeSelector() %>% 
  dyOptions(drawPoints = TRUE, pointSize = 1) %>% 
  dyRangeSelector(height = 50) %>% 
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  dyOptions(colors = RColorBrewer::brewer.pal(6, "Dark2")) %>% 
  dyUnzoom() %>% 
  dyCrosshair()

```



## Covid Tweets With Sums with 24H roll

```{r, eval=F}

data_xts %>% 
  # head(100) %>% 
  dygraph(main = "Tweets Matching The Identity Patterns") %>% 
  dyRangeSelector() %>% 
  dyOptions(drawPoints = TRUE, pointSize = 1) %>% 
  dyRangeSelector(height = 50) %>% 
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  dyOptions(colors = RColorBrewer::brewer.pal(6, "Dark2")) %>% 
  dyRoller(rollPeriod = 24) %>% 
  dyUnzoom() %>% 
  dyCrosshair()

```



## Work With Plotly


